name: Update README Cache

on:
  schedule:
    - cron: "0 */1 * * *"  # Executa a cada 1 hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate Random Number
        id: generate_random
        run: echo "RAND=$(openssl rand -hex 4)" >> $GITHUB_ENV

      - name: Print README before changes
        run: cat README.md

      - name: Update README with new rand
        run: |
          echo "Substituindo rand no README.md"
          sed -i "s|rand=[a-zA-Z0-9]*|rand=${RAND}|g" README.md

      - name: Print README after changes
        run: cat README.md

      - name: Commit changes if README was updated
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md

          echo "Git Status apos sed:"
          git status --short

          if git status --porcelain | grep -q "README.md"; then
            git commit -m "Atualizando README com novo número rand"
            git push origin main
          else
            echo "No changes detected in README.md"
          fi
